/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#005313",
        "outline-variant": "#c6c6c6",
        "on-error": "#ffffff",
        "surface": "#f9f9f9",
        "on-background": "#1a1c1c",
        "tertiary-container": "#94f990",
        "tertiary": "#006e1c",
        "surface-variant": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "surface-container-highest": "#e2e2e2",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#94f990",
        "tertiary-fixed-dim": "#78dc77",
        "on-secondary-fixed": "#261a00",
        "secondary": "#785900",
        "on-secondary-container": "#5b4300",
        "surface-container": "#eeeeee",
        "on-primary-fixed": "#001d36",
        "primary-fixed": "#d1e4ff",
        "inverse-primary": "#9ecaff",
        "primary": "#0061a4",
        "on-primary-fixed-variant": "#00497d",
        "outline": "#777777",
        "surface-dim": "#dadada",
        "error": "#ba1a1a",
        "on-surface-variant": "#474747",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#002204",
        "background": "#f9f9f9",
        "surface-container-low": "#f3f3f3",
        "on-tertiary-fixed-variant": "#005313",
        "secondary-fixed-dim": "#fabd00",
        "primary-container": "#d1e4ff",
        "inverse-on-surface": "#f1f1f1",
        "on-tertiary": "#ffffff",
        "surface-tint": "#0061a4",
        "on-primary-container": "#00497d",
        "error-container": "#ffdad6",
        "inverse-surface": "#2f3131",
        "secondary-container": "#ffdf9e",
        "secondary-fixed": "#ffdf9e",
        "on-secondary-fixed-variant": "#5b4300",
        "surface-container-high": "#e8e8e8",
        "surface-bright": "#f9f9f9",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#9ecaff"
      },
      fontFamily: {
        "headline": ["Heebo", "Plus Jakarta Sans", "sans-serif"],
        "body": ["Heebo", "Be Vietnam Pro", "sans-serif"],
        "label": ["Heebo", "Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
